// Firestore Seed Script - Foof Information System
// 100 Meals with Cyprus prices, calories, allergens, and nutrients
// Run: node seed_database.js

const { initializeApp } = require('firebase/app');
const { getFirestore, collection, addDoc, getDocs, deleteDoc, doc } = require('firebase/firestore');

const firebaseConfig = {
  apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
  authDomain: 'foof-information-system.firebaseapp.com',
  projectId: 'foof-information-system',
  storageBucket: 'foof-information-system.firebasestorage.app',
  messagingSenderId: '526611601642',
  appId: '1:526611601642:web:6dd13ff014d03ad72a5f93',
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// 100 Meals with Cyprus prices (TL - North Cyprus), calories, nutrients, allergens
const meals = [
  // ── ANA YEMEKLER (Main Dishes) ──────────────────────────────
  {
    name: 'Izgara Tavuk',
    description: 'Taze izgara tavuk göğsü, pirinç pilavı ve salata ile servis edilir.',
    price: 145.0,
    calories: 350,
    nutrients: { protein: 35.0, carbs: 45.0, fat: 8.0, fiber: 3.0 },
    allergens: [],
    stock: 25,
    imageUrl: 'assets/images/grilledchicken.jpeg',
    category: 'main',
  },
  {
    name: 'Köfte',
    description: 'El yapımı köfte, patates kızartması ve cacık ile servis edilir.',
    price: 160.0,
    calories: 420,
    nutrients: { protein: 28.0, carbs: 38.0, fat: 15.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy'],
    stock: 20,
    imageUrl: 'assets/images/meatballs.jpeg',
    category: 'main',
  },
  {
    name: 'Mantı',
    description: 'El yapımı mantı, yoğurt ve tereyağlı sos ile servis edilir.',
    price: 135.0,
    calories: 380,
    nutrients: { protein: 18.0, carbs: 55.0, fat: 12.0, fiber: 4.0 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 30,
    imageUrl: 'assets/images/manti.jpeg',
    category: 'main',
  },
  {
    name: 'Sebzeli Yemek',
    description: 'Taze mevsim sebzeleri ile hazırlanan sağlıklı ana yemek.',
    price: 115.0,
    calories: 180,
    nutrients: { protein: 8.0, carbs: 25.0, fat: 5.0, fiber: 8.0 },
    allergens: [],
    stock: 15,
    imageUrl: 'assets/images/vegetablemeal.jpeg',
    category: 'main',
  },
  {
    name: 'Lahmacun',
    description: 'İnce hamur üzerine kıymalı ve baharatlı karışım.',
    price: 85.0,
    calories: 280,
    nutrients: { protein: 12.0, carbs: 42.0, fat: 8.0, fiber: 3.0 },
    allergens: ['gluten'],
    stock: 40,
    imageUrl: 'assets/images/lahmacun.jpeg',
    category: 'main',
  },
  {
    name: 'Pide',
    description: 'Kıymalı veya kaşarlı geleneksel Türk pidesi.',
    price: 125.0,
    calories: 450,
    nutrients: { protein: 20.0, carbs: 60.0, fat: 14.0, fiber: 2.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 25,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Tavuk Şiş',
    description: 'Marine edilmiş tavuk şiş, bulgur pilavı ve domates ile.',
    price: 155.0,
    calories: 320,
    nutrients: { protein: 32.0, carbs: 30.0, fat: 10.0, fiber: 3.5 },
    allergens: [],
    stock: 20,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Kuzu Güveç',
    description: 'Fırında pişirilmiş kuzu eti, patates ve sebzeler ile.',
    price: 195.0,
    calories: 520,
    nutrients: { protein: 38.0, carbs: 35.0, fat: 22.0, fiber: 4.0 },
    allergens: [],
    stock: 15,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Moussaka',
    description: 'Kıbrıs usulü patlıcanlı moussaka, beşamel soslu.',
    price: 145.0,
    calories: 480,
    nutrients: { protein: 22.0, carbs: 30.0, fat: 28.0, fiber: 5.0 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Kuru Fasulye',
    description: 'Geleneksel tarif ile pişirilmiş kuru fasulye, pirinç pilavı ile.',
    price: 95.0,
    calories: 290,
    nutrients: { protein: 14.0, carbs: 48.0, fat: 4.0, fiber: 10.0 },
    allergens: [],
    stock: 35,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Etli Nohut',
    description: 'Dana eti ile pişirilmiş nohut yemeği, pirinç pilavı ile.',
    price: 110.0,
    calories: 310,
    nutrients: { protein: 18.0, carbs: 42.0, fat: 7.0, fiber: 8.0 },
    allergens: [],
    stock: 25,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Balık Tava',
    description: 'Taze levrek veya çipura tava, limon ve salata ile.',
    price: 185.0,
    calories: 280,
    nutrients: { protein: 30.0, carbs: 5.0, fat: 15.0, fiber: 1.0 },
    allergens: ['fish'],
    stock: 10,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Tavuk Sote',
    description: 'Biber ve soğan ile sote edilmiş tavuk, pirinç ile servis.',
    price: 135.0,
    calories: 340,
    nutrients: { protein: 30.0, carbs: 35.0, fat: 9.0, fiber: 3.0 },
    allergens: [],
    stock: 20,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'İskender Kebap',
    description: 'Döner et üzerine yoğurt ve domates sosu, tereyağı ile.',
    price: 175.0,
    calories: 550,
    nutrients: { protein: 35.0, carbs: 45.0, fat: 20.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy'],
    stock: 15,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Midye Dolma',
    description: 'Pirinçli iç harçla doldurulmuş midye, limon ile.',
    price: 120.0,
    calories: 240,
    nutrients: { protein: 15.0, carbs: 30.0, fat: 6.0, fiber: 2.0 },
    allergens: ['shellfish', 'gluten'],
    stock: 12,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Kalamar Tava',
    description: 'Çıtır kalamar halkası, tzatziki sosu ve limon ile.',
    price: 165.0,
    calories: 350,
    nutrients: { protein: 22.0, carbs: 28.0, fat: 14.0, fiber: 1.0 },
    allergens: ['shellfish', 'gluten', 'dairy'],
    stock: 10,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Tavuk Döner',
    description: 'Lezzetli tavuk döner dürüm, acılı sos ile.',
    price: 105.0,
    calories: 490,
    nutrients: { protein: 28.0, carbs: 55.0, fat: 15.0, fiber: 3.0 },
    allergens: ['gluten', 'dairy'],
    stock: 30,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Et Döner',
    description: 'Dana ve kuzu karışımı döner dürüm, sarımsaklı yoğurt ile.',
    price: 135.0,
    calories: 590,
    nutrients: { protein: 32.0, carbs: 55.0, fat: 22.0, fiber: 3.0 },
    allergens: ['gluten', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Musakka',
    description: 'Patlıcan ve kıymalı kat kat musakka, fırında pişirilmiş.',
    price: 140.0,
    calories: 460,
    nutrients: { protein: 20.0, carbs: 28.0, fat: 25.0, fiber: 6.0 },
    allergens: ['dairy', 'eggs'],
    stock: 15,
    imageUrl: '',
    category: 'main',
  },
  {
    name: 'Zeytinyağlı Enginar',
    description: 'Zeytinyağında pişirilmiş enginar, limon ile soğuk servis.',
    price: 125.0,
    calories: 150,
    nutrients: { protein: 5.0, carbs: 18.0, fat: 6.0, fiber: 7.0 },
    allergens: [],
    stock: 10,
    imageUrl: '',
    category: 'main',
  },

  // ── ÇORBALAR (Soups) ─────────────────────────────────────────
  {
    name: 'Mercimek Çorbası',
    description: 'Geleneksel kırmızı mercimek çorbası, limon ve kırmızı biber ile.',
    price: 50.0,
    calories: 180,
    nutrients: { protein: 10.0, carbs: 28.0, fat: 3.0, fiber: 8.0 },
    allergens: [],
    stock: 60,
    imageUrl: 'assets/images/soup.jpeg',
    category: 'soup',
  },
  {
    name: 'Yayla Çorbası',
    description: 'Yoğurtlu ve nane soslu pirinçli çorba.',
    price: 50.0,
    calories: 160,
    nutrients: { protein: 7.0, carbs: 22.0, fat: 4.0, fiber: 1.0 },
    allergens: ['dairy', 'gluten'],
    stock: 50,
    imageUrl: '',
    category: 'soup',
  },
  {
    name: 'Domates Çorbası',
    description: 'Taze domates ile hazırlanan kremali domates çorbası.',
    price: 50.0,
    calories: 140,
    nutrients: { protein: 4.0, carbs: 20.0, fat: 4.0, fiber: 3.0 },
    allergens: ['dairy'],
    stock: 50,
    imageUrl: '',
    category: 'soup',
  },
  {
    name: 'Ezogelin Çorbası',
    description: 'Kırmızı mercimek, bulgur ve baharatlarla pişirilmiş.',
    price: 50.0,
    calories: 195,
    nutrients: { protein: 10.0, carbs: 32.0, fat: 3.5, fiber: 7.0 },
    allergens: ['gluten'],
    stock: 40,
    imageUrl: '',
    category: 'soup',
  },
  {
    name: 'İşkembe Çorbası',
    description: 'Geleneksel işkembe çorbası, sarımsaklı sirke ile.',
    price: 55.0,
    calories: 210,
    nutrients: { protein: 15.0, carbs: 10.0, fat: 10.0, fiber: 0.0 },
    allergens: ['dairy'],
    stock: 20,
    imageUrl: '',
    category: 'soup',
  },

  // ── SALATALAR (Salads) ───────────────────────────────────────
  {
    name: 'Çoban Salatası',
    description: 'Taze domates, salatalık, soğan, zeytinyağı ve limon.',
    price: 65.0,
    calories: 80,
    nutrients: { protein: 3.0, carbs: 10.0, fat: 4.0, fiber: 3.0 },
    allergens: [],
    stock: 40,
    imageUrl: 'assets/images/salad.jpeg',
    category: 'salad',
  },
  {
    name: 'Sezar Salatası',
    description: 'Marul, parmezan, kruton ve özel sezar sos ile.',
    price: 95.0,
    calories: 180,
    nutrients: { protein: 8.0, carbs: 12.0, fat: 11.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy', 'eggs', 'fish'],
    stock: 20,
    imageUrl: '',
    category: 'salad',
  },
  {
    name: 'Ton Balıklı Salata',
    description: 'Ton balığı, mısır, domates ve zeytinyağlı yeşil salata.',
    price: 105.0,
    calories: 200,
    nutrients: { protein: 18.0, carbs: 10.0, fat: 8.0, fiber: 3.0 },
    allergens: ['fish'],
    stock: 15,
    imageUrl: '',
    category: 'salad',
  },
  {
    name: 'Rus Salatası',
    description: 'Patates, havuç, bezelye ve mayonezli geleneksel Rus salatası.',
    price: 75.0,
    calories: 250,
    nutrients: { protein: 6.0, carbs: 28.0, fat: 13.0, fiber: 4.0 },
    allergens: ['eggs', 'dairy'],
    stock: 20,
    imageUrl: '',
    category: 'salad',
  },
  {
    name: 'Söğüş Salatası',
    description: 'Haşlanmış zeytinyağlı sebzeler, limon suyu ile.',
    price: 70.0,
    calories: 120,
    nutrients: { protein: 4.0, carbs: 16.0, fat: 5.0, fiber: 5.0 },
    allergens: [],
    stock: 25,
    imageUrl: '',
    category: 'salad',
  },
  {
    name: 'Hellim Salatası',
    description: 'Izgaralanmış Kıbrıs hellimi, domates ve nane ile taze salata.',
    price: 120.0,
    calories: 220,
    nutrients: { protein: 14.0, carbs: 8.0, fat: 14.0, fiber: 2.0 },
    allergens: ['dairy'],
    stock: 15,
    imageUrl: '',
    category: 'salad',
  },

  // ── TATLILAR (Desserts) ──────────────────────────────────────
  {
    name: 'Sütlaç',
    description: 'Ev yapımı sütlaç, tarçın ile servis edilir.',
    price: 60.0,
    calories: 220,
    nutrients: { protein: 6.0, carbs: 38.0, fat: 5.0, fiber: 0.0 },
    allergens: ['dairy', 'gluten'],
    stock: 30,
    imageUrl: 'assets/images/ricepudding.jpeg',
    category: 'dessert',
  },
  {
    name: 'Baklava',
    description: 'İnce yufka katları arasında fıstıklı geleneksel Türk baklavası.',
    price: 75.0,
    calories: 400,
    nutrients: { protein: 8.0, carbs: 52.0, fat: 18.0, fiber: 2.0 },
    allergens: ['gluten', 'nuts', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Kazandibi',
    description: 'Karamelize kazandibi, geleneksel tarçınlı muhallebi.',
    price: 60.0,
    calories: 250,
    nutrients: { protein: 7.0, carbs: 40.0, fat: 6.0, fiber: 0.0 },
    allergens: ['dairy', 'gluten'],
    stock: 20,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Kadayıf',
    description: 'Tel kadayıf, kaymak ve şerbet ile geleneksel tatlı.',
    price: 65.0,
    calories: 380,
    nutrients: { protein: 6.0, carbs: 58.0, fat: 14.0, fiber: 1.0 },
    allergens: ['gluten', 'dairy', 'nuts'],
    stock: 15,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Revani',
    description: 'İrmikli Kıbrıs revani, şerbetli ve üzüm pekmezli.',
    price: 55.0,
    calories: 340,
    nutrients: { protein: 5.0, carbs: 62.0, fat: 8.0, fiber: 1.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Lokma',
    description: 'Altın renkli kızarmış hamur ve tatlı şerbet ile lokma.',
    price: 45.0,
    calories: 280,
    nutrients: { protein: 4.0, carbs: 48.0, fat: 8.0, fiber: 1.0 },
    allergens: ['gluten', 'eggs'],
    stock: 40,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Dondurma',
    description: 'Günlük taze dondurma, çikolata veya vanilyalı.',
    price: 45.0,
    calories: 200,
    nutrients: { protein: 4.0, carbs: 28.0, fat: 8.0, fiber: 0.0 },
    allergens: ['dairy'],
    stock: 50,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Fırın Sütlaç',
    description: 'Fırında karamelize edilmiş üstsü ile sütlaç.',
    price: 65.0,
    calories: 235,
    nutrients: { protein: 7.0, carbs: 40.0, fat: 5.5, fiber: 0.0 },
    allergens: ['dairy', 'gluten'],
    stock: 20,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Tiramisu',
    description: 'Mascarpone kremalı, espresso ve kakao tozlu tiramisu.',
    price: 80.0,
    calories: 350,
    nutrients: { protein: 7.0, carbs: 38.0, fat: 18.0, fiber: 0.5 },
    allergens: ['dairy', 'eggs', 'gluten'],
    stock: 15,
    imageUrl: '',
    category: 'dessert',
  },
  {
    name: 'Çikolatalı Kek',
    description: 'Sıcak çikolata soslu ve vanilya dondurmalı brownie.',
    price: 75.0,
    calories: 420,
    nutrients: { protein: 6.0, carbs: 52.0, fat: 20.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
    stock: 20,
    imageUrl: '',
    category: 'dessert',
  },

  // ── İÇECEKLER (Drinks) ──────────────────────────────────────
  {
    name: 'Ayran',
    description: 'Taze yapılmış ayran, 500ml.',
    price: 30.0,
    calories: 60,
    nutrients: { protein: 4.0, carbs: 5.0, fat: 2.0, fiber: 0.0 },
    allergens: ['dairy'],
    stock: 100,
    imageUrl: 'assets/images/ayran.jpeg',
    category: 'drink',
  },
  {
    name: 'Su',
    description: 'Doğal kaynak suyu, 500ml.',
    price: 15.0,
    calories: 0,
    nutrients: { protein: 0.0, carbs: 0.0, fat: 0.0, fiber: 0.0 },
    allergens: [],
    stock: 200,
    imageUrl: 'assets/images/su.jpeg',
    category: 'drink',
  },
  {
    name: 'Türk Çayı',
    description: 'Demlik çay, bardakta servis edilir.',
    price: 15.0,
    calories: 5,
    nutrients: { protein: 0.0, carbs: 1.0, fat: 0.0, fiber: 0.0 },
    allergens: [],
    stock: 150,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Nescafé',
    description: 'Sıcak veya soğuk Nescafé kahve, istege bağlı süt ile.',
    price: 35.0,
    calories: 40,
    nutrients: { protein: 1.0, carbs: 6.0, fat: 1.0, fiber: 0.0 },
    allergens: ['dairy'],
    stock: 80,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Türk Kahvesi',
    description: 'Geleneksel Türk tiryaki kahvesi, mastic veya sade.',
    price: 35.0,
    calories: 15,
    nutrients: { protein: 0.5, carbs: 2.0, fat: 0.0, fiber: 0.0 },
    allergens: [],
    stock: 80,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Taze Sıkma Portakal',
    description: 'Günlük taze sıkılmış portakal suyu, 500ml.',
    price: 55.0,
    calories: 110,
    nutrients: { protein: 2.0, carbs: 26.0, fat: 0.5, fiber: 1.0 },
    allergens: [],
    stock: 40,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Limonata',
    description: 'Ev yapımı taze limonata, nane ile.',
    price: 45.0,
    calories: 80,
    nutrients: { protein: 0.5, carbs: 20.0, fat: 0.0, fiber: 0.5 },
    allergens: [],
    stock: 60,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Cola',
    description: 'Soğuk Coca-Cola, 330ml kutu.',
    price: 35.0,
    calories: 140,
    nutrients: { protein: 0.0, carbs: 36.0, fat: 0.0, fiber: 0.0 },
    allergens: [],
    stock: 100,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Şalgam',
    description: 'Geleneksel Türk turplu şalgam suyu, 250ml.',
    price: 25.0,
    calories: 30,
    nutrients: { protein: 1.0, carbs: 6.0, fat: 0.0, fiber: 0.5 },
    allergens: [],
    stock: 50,
    imageUrl: '',
    category: 'drink',
  },
  {
    name: 'Soda',
    description: 'Soğuk maden sodası, 200ml.',
    price: 20.0,
    calories: 0,
    nutrients: { protein: 0.0, carbs: 0.0, fat: 0.0, fiber: 0.0 },
    allergens: [],
    stock: 100,
    imageUrl: '',
    category: 'drink',
  },

  // ── ATISTIRMALIKLAR (Snacks) ─────────────────────────────────
  {
    name: 'Sigara Böreği',
    description: 'Peynirli veya patatesli geleneksel sigara böreği.',
    price: 65.0,
    calories: 310,
    nutrients: { protein: 9.0, carbs: 35.0, fat: 14.0, fiber: 1.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 40,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Su Böreği',
    description: 'El açması peynirli su böreği, tereyağlı.',
    price: 85.0,
    calories: 380,
    nutrients: { protein: 12.0, carbs: 42.0, fat: 18.0, fiber: 1.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Poğaça',
    description: 'Zeytinli veya peynirli gevrek poğaça.',
    price: 45.0,
    calories: 260,
    nutrients: { protein: 7.0, carbs: 32.0, fat: 11.0, fiber: 1.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 50,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Simit',
    description: 'Susam kaplamalı geleneksel simit, peynir ile.',
    price: 30.0,
    calories: 220,
    nutrients: { protein: 8.0, carbs: 40.0, fat: 3.0, fiber: 3.0 },
    allergens: ['gluten', 'sesame'],
    stock: 60,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Gözleme',
    description: 'Ispanaklı ve peynirli el açması Türk gözlemesi.',
    price: 95.0,
    calories: 340,
    nutrients: { protein: 14.0, carbs: 38.0, fat: 14.0, fiber: 3.0 },
    allergens: ['gluten', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Çeşitli Ekmek Sepeti',
    description: 'Taze peksimek, beyaz ekmek ve tahin ekmeği çeşitleri.',
    price: 35.0,
    calories: 200,
    nutrients: { protein: 6.0, carbs: 38.0, fat: 3.0, fiber: 2.5 },
    allergens: ['gluten'],
    stock: 80,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Nachos & Guacamole',
    description: 'Çıtır mısır cipsi, avokado guacamole ve salsa ile.',
    price: 110.0,
    calories: 350,
    nutrients: { protein: 5.0, carbs: 38.0, fat: 18.0, fiber: 6.0 },
    allergens: ['gluten'],
    stock: 20,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Hellim Izgara',
    description: 'Sicilyalı hellim peyniri ızgarada pişirilmiş, nane ile.',
    price: 95.0,
    calories: 280,
    nutrients: { protein: 18.0, carbs: 2.0, fat: 22.0, fiber: 0.0 },
    allergens: ['dairy'],
    stock: 30,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Falafel Tabağı',
    description: 'Baharatlı nohutlu falafel, humus ve pita ekmeği ile.',
    price: 120.0,
    calories: 380,
    nutrients: { protein: 16.0, carbs: 45.0, fat: 14.0, fiber: 10.0 },
    allergens: ['gluten', 'sesame'],
    stock: 15,
    imageUrl: '',
    category: 'snack',
  },
  {
    name: 'Meze Tabağı',
    description: 'Humus, cacık, patlıcan ezmesi ve pita ekmeği ile Kıbrıs mezesi.',
    price: 150.0,
    calories: 420,
    nutrients: { protein: 14.0, carbs: 42.0, fat: 20.0, fiber: 8.0 },
    allergens: ['gluten', 'dairy', 'sesame'],
    stock: 15,
    imageUrl: '',
    category: 'snack',
  },

  // ── KAHVALTI (Breakfast) ─────────────────────────────────────
  {
    name: 'Türk Kahvaltısı',
    description: 'Zeytin, peynir, domates, salatalık, bal, tereyağı ve yumurta.',
    price: 145.0,
    calories: 450,
    nutrients: { protein: 20.0, carbs: 30.0, fat: 26.0, fiber: 4.0 },
    allergens: ['dairy', 'eggs', 'gluten'],
    stock: 20,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Sahanda Yumurta',
    description: 'Tereyağında pişirilmiş sahanda yumurta, sucuklu veya sade.',
    price: 65.0,
    calories: 220,
    nutrients: { protein: 12.0, carbs: 2.0, fat: 18.0, fiber: 0.0 },
    allergens: ['eggs', 'dairy'],
    stock: 30,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Menemen',
    description: 'Domates ve biber ile pişirilmiş yumurta, ekmek ile.',
    price: 75.0,
    calories: 250,
    nutrients: { protein: 13.0, carbs: 16.0, fat: 15.0, fiber: 3.0 },
    allergens: ['eggs', 'gluten'],
    stock: 25,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Omlet',
    description: 'Peynir, domates ve biber ile omlet.',
    price: 80.0,
    calories: 290,
    nutrients: { protein: 18.0, carbs: 4.0, fat: 22.0, fiber: 1.0 },
    allergens: ['eggs', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Sıcak Sandviç',
    description: 'Tost ekmeğinde kaşar peyniri ve salam ile sıcak sandviç.',
    price: 70.0,
    calories: 350,
    nutrients: { protein: 16.0, carbs: 36.0, fat: 15.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy'],
    stock: 30,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Granola Bowl',
    description: 'Yulaf, kuru meyve ve fındıklı granola, yoğurt ve bal ile.',
    price: 95.0,
    calories: 380,
    nutrients: { protein: 12.0, carbs: 58.0, fat: 10.0, fiber: 7.0 },
    allergens: ['dairy', 'gluten', 'nuts'],
    stock: 15,
    imageUrl: '',
    category: 'breakfast',
  },
  {
    name: 'Pancake',
    description: 'Taze pankek, akçaağaç şurubu ve meyve ile.',
    price: 90.0,
    calories: 340,
    nutrients: { protein: 8.0, carbs: 56.0, fat: 10.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'breakfast',
  },

  // ── VEJETARYEN/VEGAN (Vegetarian/Vegan) ─────────────────────
  {
    name: 'Mercimekli Köfte',
    description: 'Kırmızı mercimek ve bulgurdan yapılan vejetaryen köfte.',
    price: 85.0,
    calories: 240,
    nutrients: { protein: 10.0, carbs: 42.0, fat: 3.0, fiber: 8.0 },
    allergens: ['gluten'],
    stock: 25,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Zeytinyağlı Fasulye',
    description: 'Zeytinyağında taze fasulye ve domates ile.',
    price: 90.0,
    calories: 160,
    nutrients: { protein: 5.0, carbs: 22.0, fat: 6.0, fiber: 7.0 },
    allergens: [],
    stock: 20,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'İmam Bayıldı',
    description: 'Patlıcan, domates, soğan ve sarımsaklı zeytinyağlı yemek.',
    price: 100.0,
    calories: 200,
    nutrients: { protein: 4.0, carbs: 24.0, fat: 10.0, fiber: 7.0 },
    allergens: [],
    stock: 15,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Dolma',
    description: 'Zeytinyağlı pirinçli iç harçla doldurulmuş yaprak sarması.',
    price: 110.0,
    calories: 190,
    nutrients: { protein: 4.0, carbs: 28.0, fat: 7.0, fiber: 3.0 },
    allergens: ['gluten'],
    stock: 20,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Brokoli Çorbası',
    description: 'Kremalı brokoli çorbası, taze ekmek ile servis.',
    price: 55.0,
    calories: 150,
    nutrients: { protein: 6.0, carbs: 16.0, fat: 6.0, fiber: 5.0 },
    allergens: ['dairy'],
    stock: 30,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Tabbouleh',
    description: 'Bol maydanoz, domates, limon ve zeytinyağı ile Lübnan salatası.',
    price: 85.0,
    calories: 140,
    nutrients: { protein: 4.0, carbs: 20.0, fat: 6.0, fiber: 5.0 },
    allergens: ['gluten'],
    stock: 20,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Falafel Wrap',
    description: 'Lavaş ekmekte falafel, tahin sosu ve sebzeler.',
    price: 105.0,
    calories: 380,
    nutrients: { protein: 14.0, carbs: 50.0, fat: 14.0, fiber: 9.0 },
    allergens: ['gluten', 'sesame'],
    stock: 15,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Humus Tabağı',
    description: 'Ev yapımı humus, zeytinyağı ve pul biber ile pita ekmek.',
    price: 95.0,
    calories: 260,
    nutrients: { protein: 10.0, carbs: 32.0, fat: 12.0, fiber: 8.0 },
    allergens: ['gluten', 'sesame'],
    stock: 25,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Avokado Toast',
    description: 'Tam tahıllı ekmekte ezilmiş avokado, limon ve pul biber.',
    price: 115.0,
    calories: 310,
    nutrients: { protein: 8.0, carbs: 30.0, fat: 18.0, fiber: 8.0 },
    allergens: ['gluten'],
    stock: 15,
    imageUrl: '',
    category: 'vegetarian',
  },
  {
    name: 'Quinoa Bowl',
    description: 'Kinoa, ızgara sebzeler, tahin sosu ve nane ile protein kasesi.',
    price: 135.0,
    calories: 350,
    nutrients: { protein: 14.0, carbs: 44.0, fat: 12.0, fiber: 8.0 },
    allergens: ['sesame'],
    stock: 12,
    imageUrl: '',
    category: 'vegetarian',
  },

  // ── PILAV & YAN YEMEKLER (Rice & Sides) ─────────────────────
  {
    name: 'Pirinç Pilavı',
    description: 'Tereyağlı sade pirinç pilavı, vermicelli ile.',
    price: 45.0,
    calories: 200,
    nutrients: { protein: 4.0, carbs: 38.0, fat: 5.0, fiber: 0.5 },
    allergens: ['dairy', 'gluten'],
    stock: 80,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Bulgur Pilavı',
    description: 'Domatesli ve aşurelik buğdaylı sebzeli bulgur pilavı.',
    price: 40.0,
    calories: 190,
    nutrients: { protein: 6.0, carbs: 36.0, fat: 4.0, fiber: 4.0 },
    allergens: ['gluten'],
    stock: 70,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Patates Kızartması',
    description: 'Altın sarısı gevrek patates kızartması.',
    price: 50.0,
    calories: 320,
    nutrients: { protein: 4.0, carbs: 45.0, fat: 14.0, fiber: 3.5 },
    allergens: [],
    stock: 60,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Izgara Sebze',
    description: 'Parmezan peynirli çeşitli ızgara sebzeler.',
    price: 65.0,
    calories: 140,
    nutrients: { protein: 6.0, carbs: 18.0, fat: 5.0, fiber: 6.0 },
    allergens: ['dairy'],
    stock: 30,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Haşlanmış Sebze',
    description: 'Buharda pişirilmiş brokoli, havuç ve kabak.',
    price: 45.0,
    calories: 90,
    nutrients: { protein: 4.0, carbs: 14.0, fat: 1.0, fiber: 6.0 },
    allergens: [],
    stock: 40,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Ekmek (2 Dilim)',
    description: 'Taze beyaz veya tam buğday ekmeği, 2 dilim.',
    price: 15.0,
    calories: 140,
    nutrients: { protein: 5.0, carbs: 28.0, fat: 1.5, fiber: 1.5 },
    allergens: ['gluten'],
    stock: 120,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Makarna',
    description: 'Domates soslu penne makarna, parmezan ile.',
    price: 95.0,
    calories: 380,
    nutrients: { protein: 14.0, carbs: 60.0, fat: 8.0, fiber: 3.5 },
    allergens: ['gluten', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'side',
  },
  {
    name: 'Cacık',
    description: 'Soğuk yoğurt, salatalık, nane ve sarımsaklı cacık.',
    price: 40.0,
    calories: 80,
    nutrients: { protein: 4.0, carbs: 8.0, fat: 3.0, fiber: 0.5 },
    allergens: ['dairy'],
    stock: 50,
    imageUrl: '',
    category: 'side',
  },

  // ── FASTFOOD ─────────────────────────────────────────────────
  {
    name: 'Hamburger',
    description: '150g dana burgeri, marul, domates ve özel sos ile.',
    price: 155.0,
    calories: 540,
    nutrients: { protein: 28.0, carbs: 45.0, fat: 24.0, fiber: 2.5 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'fastfood',
  },
  {
    name: 'Tavuk Burger',
    description: 'Çıtır tavuk fileto, marul ve ranch sos ile burger.',
    price: 130.0,
    calories: 490,
    nutrients: { protein: 26.0, carbs: 48.0, fat: 18.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy', 'eggs'],
    stock: 20,
    imageUrl: '',
    category: 'fastfood',
  },
  {
    name: 'Hot Dog',
    description: 'Sosisli sandviç, hardal, ketçap ve karamelize soğan ile.',
    price: 100.0,
    calories: 410,
    nutrients: { protein: 16.0, carbs: 42.0, fat: 20.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy'],
    stock: 25,
    imageUrl: '',
    category: 'fastfood',
  },
  {
    name: 'Pizza Dilimi',
    description: 'Peynirli veya karışık pizza dilimi.',
    price: 80.0,
    calories: 300,
    nutrients: { protein: 14.0, carbs: 38.0, fat: 11.0, fiber: 2.0 },
    allergens: ['gluten', 'dairy'],
    stock: 30,
    imageUrl: '',
    category: 'fastfood',
  },
  {
    name: 'Wrap Sandviç',
    description: 'Tavuk, marul, domates ve ranch soslu dürüm wrap.',
    price: 110.0,
    calories: 420,
    nutrients: { protein: 24.0, carbs: 44.0, fat: 14.0, fiber: 3.0 },
    allergens: ['gluten', 'dairy'],
    stock: 20,
    imageUrl: '',
    category: 'fastfood',
  },
];

async function clearExistingMeals() {
  console.log('Mevcut yemekler temizleniyor...');
  const snapshot = await getDocs(collection(db, 'meals'));
  const deletePromises = snapshot.docs.map((d) => deleteDoc(doc(db, 'meals', d.id)));
  await Promise.all(deletePromises);
  console.log(`${snapshot.docs.length} eski yemek silindi.`);
}

async function seedMeals() {
  console.log('\n100 yemek Firestore\'a yükleniyor...');
  let count = 0;
  for (const meal of meals) {
    await addDoc(collection(db, 'meals'), meal);
    count++;
    process.stdout.write(`\r${count}/${meals.length} yemek yüklendi...`);
  }
  console.log(`\n✅ ${count} yemek başarıyla yüklendi!`);
}

async function main() {
  try {
    console.log('🚀 Foof Information System - Database Seed Başlıyor...');
    console.log(`📊 Toplam yemek sayısı: ${meals.length}`);
    
    await clearExistingMeals();
    await seedMeals();
    
    console.log('\n✅ Database seed tamamlandı!');
    console.log('Categories:');
    const categories = [...new Set(meals.map(m => m.category))];
    categories.forEach(cat => {
      const count = meals.filter(m => m.category === cat).length;
      console.log(`  - ${cat}: ${count} yemek`);
    });
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Hata:', error);
    process.exit(1);
  }
}

main();
