import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/review.dart';

class ReviewService extends ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  
  // Cache of reviews by meal ID
  final Map<String, List<Review>> _mealReviews = {};

  List<Review> getReviewsForMeal(String mealId) {
    return _mealReviews[mealId] ?? [];
  }

  double getAverageRating(String mealId) {
    final reviews = _mealReviews[mealId] ?? [];
    if (reviews.isEmpty) return 0.0;
    
    double total = 0.0;
    for (var review in reviews) {
      total += review.rating;
    }
    return total / reviews.length;
  }

  Future<void> fetchReviewsForMeal(String mealId) async {
    try {
      final snapshot = await _firestore
          .collection('reviews')
          .where('mealId', isEqualTo: mealId)
          .get();
          
      final reviews = snapshot.docs
          .map((doc) => Review.fromFirestore(doc.data(), doc.id))
          .toList();
          
      // Sort locally to avoid requiring composite index
      reviews.sort((a, b) => b.createdAt.compareTo(a.createdAt));
      
      _mealReviews[mealId] = reviews;
      notifyListeners();
    } catch (e) {
      debugPrint('Error fetching reviews: $e');
      if (!_mealReviews.containsKey(mealId)) {
        _mealReviews[mealId] = [];
        notifyListeners();
      }
    }
  }

  Future<void> addReview({
    required String mealId,
    required String userId,
    required String userName,
    required double rating,
    required String comment,
  }) async {
    try {
      final review = Review(
        id: '', // Will be generated by Firestore
        mealId: mealId,
        userId: userId,
        userName: userName,
        rating: rating,
        comment: comment,
        createdAt: DateTime.now(),
      );
      
      final docRef = await _firestore.collection('reviews').add(review.toFirestore());
      
      // Update local cache
      final newReview = Review(
        id: docRef.id,
        mealId: mealId,
        userId: userId,
        userName: userName,
        rating: rating,
        comment: comment,
        createdAt: review.createdAt,
      );
      
      if (_mealReviews.containsKey(mealId)) {
        _mealReviews[mealId]!.insert(0, newReview);
      } else {
        _mealReviews[mealId] = [newReview];
      }
      
      notifyListeners();
    } catch (e) {
      debugPrint('Error adding review: $e');
      rethrow;
    }
  }
}
