// File generated by FlutterFire CLI.
// Foof Information System - Firebase Configuration
// Project: foof-information-system

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    authDomain: 'foof-information-system.firebaseapp.com',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
    messagingSenderId: '526611601642',
    appId: '1:526611601642:web:6dd13ff014d03ad72a5f93',
    measurementId: 'G-P6KVYBHC79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    appId: '1:526611601642:android:47c08d17a48948c12a5f93',
    messagingSenderId: '526611601642',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    appId: '1:526611601642:ios:f57cb8429322cc2d2a5f93',
    messagingSenderId: '526611601642',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
    iosBundleId: 'com.example.ikasFis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    appId: '1:526611601642:ios:6dd13ff014d03ad72a5f93',
    messagingSenderId: '526611601642',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
    iosBundleId: 'com.example.ikasFis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    appId: '1:526611601642:web:6dd13ff014d03ad72a5f93',
    messagingSenderId: '526611601642',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAmkNHP--i5CEcNsMtZKR7fnToT50HHKvo',
    appId: '1:526611601642:web:6dd13ff014d03ad72a5f93',
    messagingSenderId: '526611601642',
    projectId: 'foof-information-system',
    storageBucket: 'foof-information-system.firebasestorage.app',
  );
}
